version: '3.8'

services:
  central-server:
    build:
      context: ./central_server
      dockerfile: Dockerfile
    container_name: fl-central-server
    ports:
      - "5000:5000"
    volumes:
      - "/home/canhdx/workspace/fl-framework/saved_model:/app/saved_models"
    environment:
      - PYTHONUNBUFFERED=1
    network_mode: host

  eu-client:
    build:
      context: ./client
      dockerfile: Dockerfile.eu
    container_name: fl-client-eu
    runtime: nvidia
    environment:
      - REGION=EU
      - CLIENT_NUM_ID=0
      - NUM_CLIENTS=3
      - SERVER_URL=http://localhost:5000  # Update to localhost
      - DATA_DIR=/data/mri_numpy
      - EXCEL_PATH=/data/labels/phenotypes.xlsx
      - SUBJECT_ID_COLUMN=subject_id  
      - LABEL_COLUMN=subject_age
      - EPOCHS_PER_ROUND=3
      - BATCH_SIZE=16
      - LEARNING_RATE=0.0001
      - NON_IID_FEATURE=Age
      - PYTHONUNBUFFERED=1
    volumes:
      - "/home/canhdx/workspace/fl-framework/server_data:/data/mri_numpy:ro"
      - "/home/canhdx/workspace/fl-framework/label.xlsx:/data/labels/phenotypes.xlsx:ro"
    network_mode: host

  asia-client:
    build:
      context: ./client
      dockerfile: Dockerfile.asia
    container_name: fl-client-asia
    runtime: nvidia
    environment:
      - REGION=ASIA
      - CLIENT_NUM_ID=1
      - NUM_CLIENTS=3
      - SERVER_URL=http://localhost:5000  # Update to localhost
      - DATA_DIR=/data/mri_numpy
      - EXCEL_PATH=/data/labels/phenotypes.xlsx
      - SUBJECT_ID_COLUMN=subject_id  
      - LABEL_COLUMN=subject_age
      - EPOCHS_PER_ROUND=3
      - BATCH_SIZE=16
      - LEARNING_RATE=0.0001
      - NON_IID_FEATURE=Age
      - PYTHONUNBUFFERED=1
    volumes:
      - "/home/canhdx/workspace/fl-framework/server_data:/data/mri_numpy:ro"
      - "/home/canhdx/workspace/fl-framework/label.xlsx:/data/labels/phenotypes.xlsx:ro"
    network_mode: host

  us-client:
    build:
      context: ./client
      dockerfile: Dockerfile.eu
    container_name: fl-client-us
    runtime: nvidia
    environment:
      - REGION=US
      - CLIENT_NUM_ID=2
      - NUM_CLIENTS=3
      - SERVER_URL=http://localhost:5000  # Update to localhost
      - DATA_DIR=/data/mri_numpy
      - EXCEL_PATH=/data/labels/phenotypes.xlsx
      - SUBJECT_ID_COLUMN=subject_id  
      - LABEL_COLUMN=subject_age
      - EPOCHS_PER_ROUND=3
      - BATCH_SIZE=16
      - LEARNING_RATE=0.0001
      - NON_IID_FEATURE=Age
      - PYTHONUNBUFFERED=1
    volumes:
      - "/home/canhdx/workspace/fl-framework/server_data:/data/mri_numpy:ro"
      - "/home/canhdx/workspace/fl-framework/label.xlsx:/data/labels/phenotypes.xlsx:ro"
    network_mode: host