_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.11
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aux_loss:
    value: ranking
batch_size:
    value: 16
beta:
    value: 1
dis_range:
    value: 5
epochs:
    value: 150
excel_path:
    value: /home/canhdx/workspace/TSAN-brain-age-estimation/label.xlsx
first_stage_net:
    value: ./model/best.pth.tar
lbd:
    value: 10
loss:
    value: mse
lr:
    value: 0.001
min_lr:
    value: 5e-06
model:
    value: ScaleDense
model_name:
    value: best_model.pth.tar
npz_name:
    value: test.npz
num_workers:
    value: 8
output_dir:
    value: /home/canhdx/workspace/TSAN-brain-age-estimation/pretrained_model/ScaleDense
plot_name:
    value: test.png
print_freq:
    value: 40
schedular:
    value: cosine
sorter:
    value: /home/canhdx/workspace/TSAN-brain-age-estimation/TSAN/Sodeep_pretrain_weight/Tied_rank_best_lstmla_slen_16.pth.tar
test_folder:
    value: /home/canhdx/workspace/TSAN-brain-age-estimation/data/test
train_folder:
    value: /home/canhdx/workspace/TSAN-brain-age-estimation/data/train
use_gender:
    value: true
valid_folder:
    value: /home/canhdx/workspace/TSAN-brain-age-estimation/data/val
warmup_epoch:
    value: 0
warmup_lr_init:
    value: 5e-07
weight_decay:
    value: 0.0005
